import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import profilePic from '../images/banksy.jpg'
import fille from '../images/fille.jpg'
import flower from '../images/flower.jpg'

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Artists - Banksy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Banksy
        </h1>
        <Image className={styles.images}
                src={profilePic}
                width={300}
                height={180}
        />
        <p className={styles.description}>
          <h3>
            Banksy est un artiste de street art qui travaille sous pseudonyme. Son véritable nom et son identité exacte sont inconnus et font toujours l'objet de spéculations
          </h3>
        </p>

        <p className={styles.description}>
            <h3>Oeuvres :</h3>
        </p>
        <Image className={styles.images}
                src={fille}
                width={420}
                height={290}
        />
        <h3>La petite fille au ballon</h3>
        <br></br>
        <Image className={styles.images}
                src={flower}
                width={420}
                height={290}
        />
        <h3>Flower Thrower</h3>
        <br></br>
        
        <Link href="./index">
          Return to the main page
        </Link>
      </main>

      <footer className={styles.footer}>
          by Uthum
      </footer>

    </div>
  )
}