import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import profilePic from '../images/boris.jpg'

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Artists - Boris Marinin</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Boris Marinin
        </h1>
        <Image className={styles.images}
                src={profilePic}
                width={300}
                height={300}
        />
        <p className={styles.description}>
          <h3>
          Boris Marinin est à la fois artiste et curateur. Il est né en 1987 à Moscou, en Russie, et a émigré en Israël en 1997. Sa démarche artistique est principalement influencée par l’auto-apprentissage et l’analyse psychanalytique. Dans son art, Boris Marinin essaie de capturer la sublimité de la nature en utilisant des formes amorphes, qui ne sont pas nécessairement liées au monde matériel que nous connaissons.
          </h3>
        </p>

        <p className={styles.description}>
            <h3>Oeuvres :</h3>
        </p>
        
        <Link href="./index">
          Return to the main page
        </Link>
      </main>

      <footer className={styles.footer}>
          by Uthum
      </footer>

    </div>
  )
}