import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import profilePic from '../images/katsushika.jpg'
import vague from '../images/vague.jpg'
import montagne from '../images/montagne.jpg'

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Artists - Katsushika Hokusai</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Katsushika Hokusai
        </h1>
        <Image className={styles.images}
                src={profilePic}
                width={220}
                height={300}
        />
        
        <p className={styles.description}>
          <h3>
          Katsushika Hokusai (葛飾 北斎, c. 31 October 1760 – 10 May 1849), known simply as Hokusai, was a Japanese artist, ukiyo-e painter and printmaker of the Edo period.
          </h3>
        </p>
        
        <p className={styles.description}>
            <h3>Oeuvres :</h3>
        </p>

        <Image className={styles.images}
                src={vague}
                width={400}
                height={280}
        />
        <h3>La vague de Kanagawa</h3>

        <Image className={styles.images}
                src={montagne}
                width={400}
                height={280}
        />
        <h3>Vent frais par matin clair</h3>
        <Link href="./index">
          Return to the main page
        </Link>
      </main>

      <footer className={styles.footer}>
          by Uthum
      </footer>

    </div>
  )
}