import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import profilePic from '../images/salvador.jpg'
import persistance from '../images/persistance.jpg'
import reve from '../images/reve.jpg'

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Artists - Salvador Dali</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Salvador Dali
        </h1>
        <Image className={styles.images}
                src={profilePic}
                width={220}
                height={300}
        />
        <p className={styles.description}>
          <h3>
          Salvador Dalí, né à Figueras le 11 mai 1904, et mort dans la même ville, le 23 janvier 1989, est un peintre, sculpteur, graveur, scénariste et écrivain catalan de nationalité espagnole. Il est considéré comme l'un des principaux représentants du surréalisme, et comme l'un des plus célèbres peintres du XXᵉ siècle.
          </h3>
        </p>
        <p className={styles.description}>
            <h3>Oeuvres :</h3>
        </p>
        <Image className={styles.images}
                src={persistance}
                width={400}
                height={290}
        />
        <h3>La persistance de la mémoire</h3>
        <br></br>

        <Image className={styles.images}
                src={reve}
                width={220}
                height={310}
        />
        <h3>Rêve causé par le vol d'une abeille autour d'une pomme grenade, une seconde avant l'éveil</h3>
        <br></br>
        <Link href="./index">
          Return to the main page
        </Link>
      </main>

      <footer className={styles.footer}>
          by Uthum
      </footer>

    </div>
  )
}